apiVersion: apps/v1
kind: Deployment
metadata:
  name: reward
  namespace: phone82
  labels:
    app: reward
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reward
  template:
    metadata:
      labels:
        app: reward
    spec:
      containers:
        - name: reward
#          image: username/reward:latest
          image: admin22.azurecr.io/reward:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 5
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m